name: Backend Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: WebApplication1
      run: docker build . -t gkadirgil/testapi:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push gkadirgil/testapi
    - name: Pull the image to VM and start it
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 165.22.72.246
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: | 
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/testapi:latest
          docker stop hello || true
          docker rm hello || true
          docker run -d -p 99:80 --name hello ${{ secrets.DOCKERHUB_USERNAME }}/testapi:latest
